Stay empty after redraw if was empty
michaeldzjap/react-signature-pad-wrapper pull request #58
Opened 2023-08-23 20:17 UTC by tfaller

Hello, 

`isEmpty()` behaved not as expected after a redraw happened.
This fixes it. `isEmpty()` is now still true after a redraw, if it was before true.

2023-08-24 06:23 UTC, michaeldzjap requested changes

2023-08-24 06:23 UTC, michaeldzjap commented on __tests__/SignaturePad.test.tsx
> +        it('is empty after redraw if was empty', () => {
```suggestion
        it('does not redraw a signature when the canvas is empty', () => {
```

2023-08-24 06:23 UTC, michaeldzjap commented on src/SignaturePad.tsx
>          if (this.props.redrawOnResize && this.signaturePad) {
```suggestion
        if (this.props.redrawOnResize && this.signaturePad && !this.signaturePad.isEmpty()) {
```

2023-08-24 06:23 UTC, michaeldzjap commented on src/SignaturePad.tsx
> +            data = !this.signaturePad.isEmpty() && this.signaturePad.toDataURL();
```suggestion
            data = this.signaturePad.toDataURL();
```

2023-08-24 06:23 UTC, michaeldzjap commented on src/SignaturePad.tsx
>          if (this.props.redrawOnResize && this.signaturePad) {
I'd prefer to include the extra condition on whether to set the `data` variable in the existing `if`. I think this is more readable than using a 2nd inline condition.

2023-08-24 06:24 UTC, michaeldzjap commented
Thanks for your PR. A couple of minor things, but overall looks good.

2023-08-24 18:00 UTC, tfaller commented
Thanks for the feedback. I've applied the changes.

2023-08-25 05:54 UTC, michaeldzjap approved these changes

2023-08-25 05:59 UTC, merged